### ISSUE TITLE
添加mip.js引入位置校验

### ISSUE THREAD

**Issue by jennyliang220** [mipengine/mip-validator#3]
保证mip.js在mip组件之前引入，防止组件js报错。一次性解决截图中的问题：
![124e1f6b-5649-4d07-b4d0-3cd8749d5c5d](https://cloud.githubusercontent.com/assets/8498677/21969811/282b2c08-dbdc-11e6-8d77-26768ec2fac3.png)

**Comment by harttle** [comment]
顺序是语义级别的校验（所以可以认为 mip 语法上是没问题的，是站长代码的 bug），可能会显著影响校验速度，因为每项这样的规则都需要遍历整个 DOM。

待讨论。
